source: _source

title: "OSGeo Glossary (Geolexica)"

google_analytics:
  id: UA-168998071-3

committee:
  name: OSGeo
  parent_org_name: OSGeo
  home: https://www.osgeo.org
  main_logo:
    path: /assets/osgeo-emblem-cmyk.svg
    alt_text: OSGeo
  footer_logo:
    path: /assets/osgeo-logo-cmyk.svg
    alt_text: OSGeo
    url: https://www.osgeo.org/

font_awesome_kit_url: https://kit.fontawesome.com/77a8a07e0a.js

has_brand_name: yes
always_show_committee_link_on_landing: yes

email: open.source@ribose.com

tagline: >-
  OSGeo Glossary

description: >-
  The authoritative glossary for OSGeo.

baseurl: ""
url: "https://osgeo.geolexica.org"

social:
  links:
    - url: https://twitter.com/osgeo
    - url: https://github.com/osgeo

# algolia:
#   application_id: NOP
#   index_name: NOP
#   search_only_api_key: NOP

nav:
  items:
  - id: concepts
    url: /concepts
    title: Concepts
    description: List of all concepts
  - id: posts
    url: /posts
    title: News & Articles
  - id: stats
    url: /stats
    title: Statistics
    description: Per-language term statistics
  - id: about
    url: /about
    title: About
  # - id: feedback
  #   url: /feedback
  #   title: Feedback

footer_nav:
  - url: https://www.osgeo.org
    title: OSGeo

powered_by:
  url: https://open.ribose.com
  title: Ribose
  logo_path: /assets/logo-ribose.svg

theme: jekyll-geolexica

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      show_header_meta: true

geolexica:
  glossary_path: "../osgeo-glossary/geolexica-v2"
  concepts_glob: "../osgeo-glossary/geolexica-v2/*.yaml"
  term_languages:
    - eng
  formats:
    - html
    - json
    - json-ld
    - tbx-iso-tml
    - turtle

tidy_json:
  pretty: true

plugins:
  - jekyll-data
  - jekyll-feed
  - jekyll-geolexica
  - jekyll-sitemap
  - jekyll-tidy-json
  - jekyll-plugin-frontend-build
