= Geolexica: OSGeo Glossary

image:https://github.com/geolexica/osgeo.geolexica.org/workflows/build/badge.svg["Build Status", link="https://github.com/osgeo.geolexica.org/actions?workflow=build"]

image:https://github.com/geolexica/osgeo.geolexica.org/workflows/deploy-master/badge.svg["Build Status", link="https://github.com/osgeo.geolexica.org/actions?workflow=deploy-master"]

image:https://github.com/geolexica/osgeo.geolexica.org/workflows/deploy-staging/badge.svg["Build Status", link="https://github.com/osgeo.geolexica.org/actions?workflow=deploy-staging"]


== Introduction

This repository provides all necessary information for the
https://osgeo.geolexica.org site.

The site is managed by OSGeo and operated by Geolexica/Ribose.

These branches of the site are deployed at:

`master`:: https://osgeo.geolexica.org
`staging`:: https://osgeodev.geolexica.org


NOTE: This repository is only meant for internal consumption!


== Structure (and how it works)

=== General

There are two types of entries in this site:

. Concepts

. Terms, which represent concepts in a certain language


[[concepts]]
=== Concepts

Every concept is recognized by a unique ID (the "`term id`"), and contains terms
in different languages.

Here's an example of it from the `_concepts/` directory (which has to be built).

[source,yaml]
----
eng:
  id: 2
  term: do-ocracy
  alt: preferred
  definition: principle where the person who volunteers to do the work
    gets to decide how it gets done
  language_code: eng
  notes: []
  examples: []
  entry_status: valid
  authoritative_source:
  lineage_source:
  lineage_source_similarity: 1
  date_accepted: 2008-11-15 00:00:00.000000000 +08:00
  review_date: 2013-01-29 00:00:00.000000000 +08:00
  review_status: final
  review_decision: accepted
  review_decision_date: 2016-10-01 00:00:00.000000000 +08:00
  review_decision_event: ...
  review_decision_notes: ...
  release: '2'
ara:
  ...
----


=== Term

A term contains multiple attributes, such as:

[source,yaml]
----
id: 2
term: abbreviation
alt: preferred
definition: designation formed by omitting words or letters from a longer form and
  designating the same concept
language_code: eng
notes: []
examples: []
entry_status: valid
authoritative_source: ISO 1087-1:2000, 3.4.9
...
----


=== Rendering of HTML


Jekyll is used to render YAML into HTML.

NOTE: Since Jekyll Collections have this flaw where YAML files can't be directly
rendered, a hack is implemented in the Makefile `_concepts` target,
so that every YAML file is converted into AsciiDoc by padding `---` at the end.


== Usage


=== How to add/remove entries or suggest changes?

This terminology database is managed by OSGeo.
Please submit proposed changes either as new Issues or Pull Requests.


== Internal operations

NOTE: These steps are only intended for the internal operator of the site!


=== Building the index

[source,sh]
----
make dist-clean
make _site
----


=== Deployment

Please push all changes to the `staging` branch, and changes will be automatically deployed and reflected on the staging site.

If your changes are to be made public to the production site, please contact Geolexica/Ribose.

These branches of the site are deployed at:

`master`:: https://osgeo.geolexica.org
`staging`:: https://osgeodev.geolexica.org


== Contributing

=== Contributing new entries (concepts/terms/translations)

Please either:

. File an Issue with description of what you are proposing,
  the managers will create a pull request for you; or

. Better yet, directly create a Pull Request to the `/concepts_data`
  folder, allowing direct review and merging of the PR. Please
  see existing `/concept_data` YAML files for the correct format
  or the example at <<concepts>>.


=== Modification of existing entries

Please either:

. File an Issue with description of what you would like to change,
  the managers will create a pull request for you; or

. Directly create a Pull Request to the particular
  `/concepts_data/{entry}.yaml` file with your modifications.


