= Geolexica: OSGeo Glossary Website

image:https://img.shields.io/github/workflow/status/geolexica/osgeo.geolexica.org/deploy-master?label=production%20deployment&style=flat-square[Production Deployment Status]
image:https://img.shields.io/github/workflow/status/geolexica/osgeo.geolexica.org/deploy-staging?label=staging%20deployment&style=flat-square[Staging Deployment Status]
image:https://img.shields.io/github/workflow/status/geolexica/osgeo.geolexica.org/build?label=build&style=flat-square[Build Status]

== Introduction

This repository provides all necessary information for the
https://osgeo.geolexica.org site.

The site is managed by OSGeo and operated by Geolexica/Ribose.

These branches of the site are deployed at:

`master`:: https://osgeo.geolexica.org
`staging`:: https://osgeodev.geolexica.org


NOTE: This repository is only meant for internal consumption!


== Structure (and how it works)

=== General

There are two types of entries in this site:

. Concepts

. Terms, which represent concepts in a certain language


[[concepts]]
=== Concepts

Every concept is recognized by a unique ID (the "`term id`"), and contains terms
in different languages.

Here's an example of it from the `_concepts/` directory (which has to be built).

[source,yaml]
----
eng:
  id: 2
  term: do-ocracy
  alt: preferred
  definition: principle where the person who volunteers to do the work
    gets to decide how it gets done
  language_code: eng
  notes: []
  examples: []
  entry_status: valid
  authoritative_source:
  lineage_source:
  lineage_source_similarity: 1
  date_accepted: 2008-11-15 00:00:00.000000000 +08:00
  review_date: 2013-01-29 00:00:00.000000000 +08:00
  review_status: final
  review_decision: accepted
  review_decision_date: 2016-10-01 00:00:00.000000000 +08:00
  review_decision_event: ...
  review_decision_notes: ...
  release: '2'
ara:
  ...
----


=== Term

A term contains multiple attributes, such as:

[source,yaml]
----
id: 2
term: abbreviation
alt: preferred
definition: designation formed by omitting words or letters from a longer form and
  designating the same concept
language_code: eng
notes: []
examples: []
entry_status: valid
authoritative_source: ISO 1087-1:2000, 3.4.9
...
----


=== Rendering of HTML


Jekyll is used to render YAML into HTML.

NOTE: Since Jekyll Collections have this flaw where YAML files can't be directly
rendered, a hack is implemented in the Makefile `_concepts` target,
so that every YAML file is converted into AsciiDoc by padding `---` at the end.


== Usage


=== How to add/remove entries or suggest changes?

This terminology database is managed by OSGeo.
Please submit proposed changes either as new Issues or Pull Requests.


== Internal operations

NOTE: These steps are only intended for the internal operator of the site!

Make sure glossary database submodule is initialized & updated.


=== Building the index

[source,sh]
----
make dist-clean
make _site
----


=== Deployment

Please push all changes to the `staging` branch, and changes will be automatically deployed and reflected on the staging site.

If your changes are to be made public to the production site, please contact Geolexica/Ribose.

These branches of the site are deployed at:

`master`:: https://osgeo.geolexica.org
`staging`:: https://osgeodev.geolexica.org


== Contributing

=== Contributing new entries (concepts/terms/translations)

Please file an issue with description of what you are proposing,
or (better) create a pull request, in the `osgeo-glossary` repository.

See the existing YAML files under `concepts/` for the correct format.


=== Modification of existing entries

Please file an issue with description of what you would like to change,
or (better) create a pull request, in the `osgeo-glossary` repository.
