---
layout: base-page
title: About
permalink: /about/
bodyClass: page
nav_items: [concepts, posts, stats, feedback, registers]
---
:page-liquid:

The OSGeo Geolexica is the online glossary for https://www.osgeo.org[OSGeo].


== Responsibility

The OSGeo Glossary is managed by the
https://wiki.osgeo.org/wiki/Lexicon_Committee[OSGeo Lexicon Committee].

////
The MLGT is managed by the ISO/TC 211 Terminology Maintenance Group (TMG).
The convenor of the TMG is Mr. Reese Plews of Japan.

Geolexica is jointly managed by the TMG and https://www.ribose.com[Ribose],
the official ISO/TC 211 web service provider and
Registration Authority of the
https://geodetic.isotc211.org[ISO Geodetic Register].
////


== Feedback

////
Feedback for Geolexica can be submitted on the
link:/feedback[Feedback] page.

Identified issues that are publicly visible are maintained at the
https://github.com/geolexica/TMG/issues[TMG GitHub Issues] page.

////


== Copyright

(C) {{ site.time | date: "%Y" }} OSGeo

All rights reserved. Unless otherwise specified, no part of this
site or its documents may be reproduced or utilized otherwise in any form or by any
means, electronic or mechanical, including photocopying, or posting on the
internet or an intranet, without prior written permission. Permission can
be requested from the address below.

[%hardbreaks]
OSGeo
9450 SW Gemini Dr. #42523
Beaverton, Oregon
United States
97008
https://www.osgeo.org/[www.osgeo.org]
